/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as saveWaterBadgeSol from "./SaveWaterBadge.sol";
export type { saveWaterBadgeSol };
export type { SaveWater } from "./SaveWater";
