/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as saveWaterBadgeSol from "./SaveWaterBadge.sol";
export { SaveWater__factory } from "./SaveWater__factory";
