/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISaveWater__factory } from "./ISaveWater__factory";
export { SaveWaterBadge__factory } from "./SaveWaterBadge__factory";
