/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISaveWater,
  ISaveWaterInterface,
} from "../../../contracts/SaveWaterBadge.sol/ISaveWater";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserCount",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISaveWater__factory {
  static readonly abi = _abi;
  static createInterface(): ISaveWaterInterface {
    return new Interface(_abi) as ISaveWaterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISaveWater {
    return new Contract(address, _abi, runner) as unknown as ISaveWater;
  }
}
